---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-alloy
    chart: grafana/alloy
    version: 0.7.0
    namespace: monitoring
    createNamespace: true
    labels:
      type: monitoring
