---
name: Linting
run-name: Linting files in `${{ github.head_ref || github.ref_name }}`

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: read-all

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linting files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      packages: read
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.LINTER_ACTION }}
          fetch-depth: 0

      - name: Super-Linter
        id: linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.LINTER_ACTION }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITLEAKS: true
          VALIDATE_KUBERNETES_KUBECONFORM: true
          VALIDATE_MARKDOWN: true
          FIX_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          # VALIDATE_RENOVATE: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
          FIX_YAML_PRETTIER: true

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Print gitconfig
        run: git config --global --list

        # Run only on:
        # - Pull requests
        # - Not on the default branch
      - name: Commit and push linting fixes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        with:
          commit_message: "chore: fix linting issues [skip ci]"
          # commit_options: "--no-verify --signoff"
          # commit_user_email: ${{ steps.gpg.outputs.email }}
          # commit_user_name: ${{ steps.gpg.outputs.name }}
