---
# Reference: https://github.com/release-drafter/release-drafter#action-inputs

name: Release Drafter
run-name: "PR: `${{ github.event.pull_request.title }}`"

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  draft:
    name: Update release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
